version: "3.8"

services:
  # Node.js API Service
  node-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9600:9600"
    volumes:
      - ./src/node:/usr/src/app/src/node
      - /usr/src/app/node_modules
    environment:
      - PORT=9600
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/confetti
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/confetti
      - PYTHON_API_URL=http://python-api:5600
      - FRONTEND_URL=http://localhost:3000
      - JWT_ACCESS_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      - JWT_ACCESS_SECRET=2fa88006305c434c8457012bb6ddfc27a6118475e8c07616c69067011583de7c0fe560d5ba565256682b446bc85705b9c62bfe5b6e87f336d86d4816942fff2b
      - JWT_REFRESH_SECRET=7c89a8dfc691825da63c2b90a352af373894905f6fd03a45fa45239f9ff81a8c7d9143069f44f6e6d8299b1b948f1d36f9f0424571c5b9ff577dc8978f2c7f5c
      - SMTP_HOST=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=hello@tripmatch.io
      - SMTP_PASSWORD=Ginger@1232025*
      - FROM_EMAIL=hello@tripmatch.io
      - FROM_NAME=Confetti
      - FLUTTERWAVE_PUBLIC_KEY=FLWPUBK_TEST-ed6b4efe39238d2007c9ff6ed99636a1-X
      - FLUTTERWAVE_SECRET_KEY=FLWSECK_TEST-2658b0a47561dad46f281804f909ab18-X
      - FLUTTERWAVE_ENCRYPTION_KEY=FLWSECK_TEST682ea6a0fa12
    depends_on:
      - mongodb
      - postgres
      - redis
    container_name: confetti-node-api
    networks:
      - confetti-network

  # Python AI/ML Service
  python-api:
    build:
      context: ./src/python
      dockerfile: Dockerfile
    ports:
      - "5600:5600"
    volumes:
      - ./src/python:/usr/src/app/src/python
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/confetti
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    container_name: confetti-python-api
    networks:
      - confetti-network

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: confetti-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=confetti
    networks:
      - confetti-network

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: confetti-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=confetti
    networks:
      - confetti-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: confetti-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - confetti-network

volumes:
  mongodb_data:
  redis_data:
  postgres_data:

networks:
  confetti-network:
    driver: bridge
